"""Primary Migration

Revision ID: 181cde65c2ad
Revises: a8e369b8635c
Create Date: 2025-08-07 20:12:03.949400

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = '181cde65c2ad'
down_revision: Union[str, Sequence[str], None] = 'a8e369b8635c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
